version: "3.7"
services:
    db:
        image: postgres:latest
        container_name: db-pwa
        restart: unless-stopped
        environment:
            POSTGRES_DATABASE: ${DB_DATABASE}
            POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: db
        ports:
            - "5450:5432"
        networks:
            - laravel

    api:
        build:
            args:
                user: jb
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel
        container_name: api-pwa
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: nginx-pwa
        restart: unless-stopped
        ports:
            - "9090:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
